# Generated by Django 2.2.9 on 2020-01-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('descritpion', models.CharField(max_length=255)),
                ('discount', models.FloatField()),
            ],
        ),
    ]
